package com.phanta.waladom.utiles;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
public class CountryCodeUtil {

    private static final Map<String, String> COUNTRY_CODES;

    static {
        Map<String, String> codes = new HashMap<>();
        codes.put("Afghanistan", "93");
        codes.put("Åland Islands", "358");
        codes.put("Albania", "355");
        codes.put("Algeria", "213");
        codes.put("American Samoa", "1-684");
        codes.put("Andorra", "376");
        codes.put("Angola", "244");
        codes.put("Anguilla", "1-264");
        codes.put("Antarctica", "672");
        codes.put("Antigua and Barbuda", "1-268");
        codes.put("Argentina", "54");
        codes.put("Armenia", "374");
        codes.put("Aruba", "297");
        codes.put("Australia", "61");
        codes.put("Austria", "43");
        codes.put("Azerbaijan", "994");
        codes.put("Bahamas", "1-242");
        codes.put("Bahrain", "973");
        codes.put("Bangladesh", "880");
        codes.put("Barbados", "1-246");
        codes.put("Belarus", "375");
        codes.put("Belgium", "32");
        codes.put("Belize", "501");
        codes.put("Benin", "229");
        codes.put("Bermuda", "1-441");
        codes.put("Bhutan", "975");
        codes.put("Bolivia", "591");
        codes.put("Bosnia and Herzegovina", "387");
        codes.put("Botswana", "267");
        codes.put("Bouvet Island", "none"); // Bouvet Island doesn't have a phone code.
        codes.put("Brazil", "55");
        codes.put("British Indian Ocean Territory", "246");
        codes.put("Brunei Darussalam", "673");
        codes.put("Bulgaria", "359");
        codes.put("Burkina Faso", "226");
        codes.put("Burundi", "257");
        codes.put("Cambodia", "855");
        codes.put("Cameroon", "237");
        codes.put("Canada", "1");
        codes.put("Cape Verde", "238");
        codes.put("Cayman Islands", "1-345");
        codes.put("Central African Republic", "236");
        codes.put("Chad", "235");
        codes.put("Chile", "56");
        codes.put("China", "86");
        codes.put("Christmas Island", "61");
        codes.put("Cocos (Keeling) Islands", "61");
        codes.put("Colombia", "57");
        codes.put("Comoros", "269");
        codes.put("Congo", "242"); // Republic of the Congo
        codes.put("Congo, The Democratic Republic of the", "243");
        codes.put("Cook Islands", "682");
        codes.put("Costa Rica", "506");
        codes.put("Cote D'Ivoire", "225");
        codes.put("Croatia", "385");
        codes.put("Cuba", "53");
        codes.put("Cyprus", "357");
        codes.put("Czech Republic", "420");
        codes.put("Denmark", "45");
        codes.put("Djibouti", "253");
        codes.put("Dominica", "1-767");
        codes.put("Dominican Republic", "1-809");
        codes.put("Ecuador", "593");
        codes.put("Egypt", "20");
        codes.put("El Salvador", "503");
        codes.put("Equatorial Guinea", "240");
        codes.put("Eritrea", "291");
        codes.put("Estonia", "372");
        codes.put("Ethiopia", "251");
        codes.put("Falkland Islands (Malvinas)", "500");
        codes.put("Faroe Islands", "298");
        codes.put("Fiji", "679");
        codes.put("Finland", "358");
        codes.put("France", "33");
        codes.put("French Guiana", "594");
        codes.put("French Polynesia", "689");
        codes.put("French Southern Territories", "262");
        codes.put("Gabon", "241");
        codes.put("Gambia", "220");
        codes.put("Georgia", "995");
        codes.put("Germany", "49");
        codes.put("Ghana", "233");
        codes.put("Gibraltar", "350");
        codes.put("Greece", "30");
        codes.put("Greenland", "299");
        codes.put("Grenada", "1-473");
        codes.put("Guadeloupe", "590");
        codes.put("Guam", "1-671");
        codes.put("Guatemala", "502");
        codes.put("Guernsey", "44");
        codes.put("Guinea", "224");
        codes.put("Guinea-Bissau", "245");
        codes.put("Guyana", "592");
        codes.put("Haiti", "509");
        codes.put("Heard Island and Mcdonald Islands", "672");
        codes.put("Holy See (Vatican City State)", "379");
        codes.put("Honduras", "504");
        codes.put("Hong Kong", "852");
        codes.put("Hungary", "36");
        codes.put("Iceland", "354");
        codes.put("India", "91");
        codes.put("Indonesia", "62");
        codes.put("Iran, Islamic Republic Of", "98");
        codes.put("Iraq", "964");
        codes.put("Ireland", "353");
        codes.put("Isle of Man", "44");
        codes.put("Israel", "972");
        codes.put("Italy", "39");
        codes.put("Jamaica", "1-876");
        codes.put("Japan", "81");
        codes.put("Jersey", "44");
        codes.put("Jordan", "962");
        codes.put("Kazakhstan", "7");
        codes.put("Kenya", "254");
        codes.put("Kiribati", "686");
        codes.put("Korea, Democratic People'S Republic of", "850");
        codes.put("Korea, Republic of", "82");
        codes.put("Kuwait", "965");
        codes.put("Kyrgyzstan", "996");
        codes.put("Lao People'S Democratic Republic", "856");
        codes.put("Latvia", "371");
        codes.put("Lebanon", "961");
        codes.put("Lesotho", "266");
        codes.put("Liberia", "231");
        codes.put("Libyan Arab Jamahiriya", "218");
        codes.put("Liechtenstein", "423");
        codes.put("Lithuania", "370");
        codes.put("Luxembourg", "352");
        codes.put("Macao", "853");
        codes.put("Macedonia, The Former Yugoslav Republic of", "389");
        codes.put("Madagascar", "261");
        codes.put("Malawi", "265");
        codes.put("Malaysia", "60");
        codes.put("Maldives", "960");
        codes.put("Mali", "223");
        codes.put("Malta", "356");
        codes.put("Marshall Islands", "692");
        codes.put("Martinique", "596");
        codes.put("Mauritania", "222");
        codes.put("Mauritius", "230");
        codes.put("Mayotte", "262");
        codes.put("Mexico", "52");
        codes.put("Micronesia, Federated States of", "691");
        codes.put("Moldova, Republic of", "373");
        codes.put("Monaco", "377");
        codes.put("Mongolia", "976");
        codes.put("Montserrat", "1-664");
        codes.put("Morocco", "212");
        codes.put("Mozambique", "258");
        codes.put("Myanmar", "95");
        codes.put("Namibia", "264");
        codes.put("Nauru", "674");
        codes.put("Nepal", "977");
        codes.put("Netherlands", "31");
        codes.put("Netherlands Antilles", "599");
        codes.put("New Caledonia", "687");
        codes.put("New Zealand", "64");
        codes.put("Nicaragua", "505");
        codes.put("Niger", "227");
        codes.put("Nigeria", "234");
        codes.put("Niue", "683");
        codes.put("Norfolk Island", "672");
        codes.put("Northern Mariana Islands", "1");
        codes.put("Norway", "47");
        codes.put("Oman", "968");
        codes.put("Pakistan", "92");
        codes.put("Palau", "680");
        codes.put("Palestinian Territory, Occupied", "970");
        codes.put("Panama", "507");
        codes.put("Papua New Guinea", "675");
        codes.put("Paraguay", "595");
        codes.put("Peru", "51");
        codes.put("Philippines", "63");
        codes.put("Pitcairn", "870");
        codes.put("Poland", "48");
        codes.put("Portugal", "351");
        codes.put("Puerto Rico", "1");
        codes.put("Qatar", "974");
        codes.put("Reunion", "262");
        codes.put("Romania", "40");
        codes.put("Russian Federation", "7");
        codes.put("RWANDA", "250");
        codes.put("Saint Helena", "290");
        codes.put("Saint Kitts and Nevis", "1");
        codes.put("Saint Lucia", "1");
        codes.put("Saint Pierre and Miquelon", "508");
        codes.put("Saint Vincent and the Grenadines", "1");
        codes.put("Samoa", "685");
        codes.put("San Marino", "378");
        codes.put("Sao Tome and Principe", "239");
        codes.put("Saudi Arabia", "966");
        codes.put("Senegal", "221");
        codes.put("Serbia and Montenegro", "381");
        codes.put("Seychelles", "248");
        codes.put("Sierra Leone", "232");
        codes.put("Singapore", "65");
        codes.put("Slovakia", "421");
        codes.put("Slovenia", "386");
        codes.put("Solomon Islands", "677");
        codes.put("Somalia", "252");
        codes.put("South Africa", "27");
        codes.put("South Georgia and the South Sandwich Islands", "500");
        codes.put("Spain", "34");
        codes.put("Sri Lanka", "94");
        codes.put("Sudan", "249");
        codes.put("Suriname", "597");
        codes.put("Svalbard and Jan Mayen", "47");
        codes.put("Swaziland", "268");
        codes.put("Sweden", "46");
        codes.put("Switzerland", "41");
        codes.put("Syrian Arab Republic", "963");
        codes.put("Taiwan, Province of China", "886");
        codes.put("Tajikistan", "992");
        codes.put("Tanzania, United Republic of", "255");
        codes.put("Thailand", "66");
        codes.put("Timor-Leste", "670");
        codes.put("Togo", "228");
        codes.put("Tokelau", "690");
        codes.put("Tonga", "676");
        codes.put("Trinidad and Tobago", "1");
        codes.put("Tunisia", "216");
        codes.put("Turkey", "90");
        codes.put("Turkmenistan", "993");
        codes.put("Turks and Caicos Islands", "1");
        codes.put("Tuvalu", "688");
        codes.put("Uganda", "256");
        codes.put("Ukraine", "380");
        codes.put("United Arab Emirates", "971");
        codes.put("United Kingdom", "44");
        codes.put("United States", "1");
        codes.put("United States Minor Outlying Islands", "1");
        codes.put("Uruguay", "598");
        codes.put("Uzbekistan", "998");
        codes.put("Vanuatu", "678");
        codes.put("Venezuela", "58");
        codes.put("Vietnam", "84");
        codes.put("Virgin Islands, British", "1");
        codes.put("Virgin Islands, U.S.", "1");
        codes.put("Wallis and Futuna", "681");
        codes.put("Western Sahara", "212");
        codes.put("Yemen", "967");
        codes.put("Zambia", "260");
        codes.put("Zimbabwe", "263");


        COUNTRY_CODES = Collections.unmodifiableMap(codes);
    }

    public static String getCountryCode(String countryName) {
        String toLower = countryName.toLowerCase();
        String code = COUNTRY_CODES.get(toLower.substring(0, 1).toUpperCase() + toLower.substring(1).toLowerCase());
        if (code == null) {
            throw new IllegalArgumentException("This is un Unknown country: " + countryName);
        }
        return code;
    }

    public static Map<String, String> getAllCountryCodes() {
        return new HashMap<>(COUNTRY_CODES); // Return a copy to prevent modifications
    }

    public static void main(String[] args) {
        System.out.println("Sudan: " + getCountryCode("SUDAN"));  // Output: 249
        System.out.println("France: " + getCountryCode("FRANCE"));  // Output: 33

        System.out.println("\nAll Countries and Codes:");
        getAllCountryCodes().forEach((country, code) ->
                System.out.println(country + " -> " + code)
        );
    }
}
